In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [7]:
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0         True
1    15810944   35            20000          0         True
2    15668575   26            43000          0        False
3    15603246   27            57000          0        False
4    15804002   19            76000          0         True
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1        False
396  15706071   51            23000          1         True
397  15654296   50            20000          1        False
398  15755018   36            33000          0         True
399  15594041   49            36000          1        False

[400 rows x 5 columns]

In [9]:
dataset=dataset.drop("User ID",axis=1)

In [11]:
dataset

Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0         True
1     35            20000          0         True
2     26            43000          0        False
3     27            57000          0        False
4     19            76000          0         True
..   ...              ...        ...          ...
395   46            41000          1        False
396   51            23000          1         True
397   50            20000          1        False
398   36            33000          0         True
399   49            36000          1        False

[400 rows x 4 columns]

In [13]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [15]:
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [17]:
independent=dataset[['Age', 'EstimatedSalary', 'Gender_Male']]
dependent=dataset[[ 'Purchased']]

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [20]:
X_train

Age  EstimatedSalary  Gender_Male
92    26            15000         True
223   60           102000         True
234   38           112000        False
232   40           107000         True
377   42            53000        False
..   ...              ...          ...
323   48            30000        False
192   29            43000         True
117   36            52000         True
47    27            54000        False
172   26           118000        False

[280 rows x 3 columns]

In [23]:
dependent.shape


(400, 1)

In [25]:
dataset.shape

(400, 4)

In [27]:
dependent

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [29]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()


In [31]:
classifier.fit(X_train,y_train)

C:\Users\sathi\anaconda3\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [33]:
y_pred=classifier.predict(X_test)

In [35]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [37]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [39]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.95      0.94      0.94        79
           1       0.88      0.90      0.89        41

    accuracy                           0.93       120
   macro avg       0.91      0.92      0.92       120
weighted avg       0.93      0.93      0.93       120



In [41]:
print(cm)

[[74  5]
 [ 4 37]]


In [43]:
#[['Age', 'EstimatedSalary', 'Gender_Male']]

In [47]:
Age_input=float(input("Age="))
EstimatedSalary_input=float(input("EstimatedSalary="))
Gender_Male_input=str(input("Gender_Male, 1-Male, 0-Female="))

Age= 45
EstimatedSalary= 29
Gender_Male, 1-Male, 0-Female= 1


In [49]:
result=classifier.predict([[Age_input,EstimatedSalary_input,Gender_Male_input]])

C:\Users\sathi\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [51]:
result

array([1], dtype=int64)

In [53]:
print(result)

[1]


In [55]:
import pickle

In [79]:
filename="finalized_RF_classifeid_model.sav"

In [81]:
pickle.dump(classifier,open(filename,'wb'))

In [83]:
loaded_model=pickle.load(open("finalized_RF_classifeid_model.sav",'rb'))

In [87]:
result=loaded_model.predict([[45,15000,1]])

C:\Users\sathi\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [89]:
result

array([1], dtype=int64)