In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [15]:
dataset = pd.read_csv("Social_Network_Ads.csv")

In [17]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [19]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [21]:
independent=dataset[['Age', 'EstimatedSalary', 'Gender_Male']]
dependent=dataset[[ 'Purchased']]

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)


In [25]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [27]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
param_grid={'C':[1,10,100,1000,2000,3000],'kernel':['poly', 'rbf', 'sigmoid'], 'gamma':['scale', 'auto'],'probability':[True]}
classifier=GridSearchCV(SVC(),param_grid,n_jobs=-1, refit=True, verbose=3,scoring='f1_weighted')
        


In [29]:
classifier=classifier.fit(X_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits


C:\Users\sathi\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [31]:
classifier

GridSearchCV(estimator=SVC(), n_jobs=-1,
             param_grid={'C': [1, 10, 100, 1000, 2000, 3000],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['poly', 'rbf', 'sigmoid'],
                         'probability': [True]},
             scoring='f1_weighted', verbose=3)

In [33]:
y_pred=classifier.predict(X_test)

In [35]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[72  7]
 [ 4 37]]


In [37]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.95      0.91      0.93        79
           1       0.84      0.90      0.87        41

    accuracy                           0.91       120
   macro avg       0.89      0.91      0.90       120
weighted avg       0.91      0.91      0.91       120



In [39]:
from sklearn.metrics import roc_auc_score
rac=roc_auc_score(y_test,classifier.predict_proba(X_test)[:,1])

In [37]:
rac

0.9632602655140475

In [48]:
from sklearn.metrics import f1_score
f1_scor=f1_score(y_test,y_pred,average='weighted')

In [50]:
print(f1_scor)

0.9090638836179633


In [52]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,classifier.predict_proba(X_test)[:,1])

0.9632602655140475

In [58]:
re=classifier.cv_results_
table=pd.DataFrame.from_dict(re)
table

In [86]:
#without applying standardisation:
Nostdresult=classifier.predict([[45,20000,1]])

In [88]:
result

array([1], dtype=int64)

In [94]:
#Appluing stadardisation
preinput=sc.fit_transform([[45,20000,1]])

In [96]:
stsresult=classifier.predict(preinput)

In [98]:
stdresult

array([1], dtype=int64)

In [146]:
import pickle
filename="Finalized_SVM_model.sav"
pickle.dump(classifier,open(filename,'wb'))

In [148]:
loaded_model=pickle.load(open("Finalized_SVM_model.sav",'rb'))

In [150]:
age_input=float(input("Age="))
EstimatedSalary_input=int(input("Estimated_Salary="))
Gender_Male_input=int(input("Gender_Male, 1-Male, 0-Female="))

Age= 45
Estimated_Salary= 20000
Gender_Male, 1-Male, 0-Female= 1


In [152]:
stdresult=classifier.predict([[age_input,EstimatedSalary_input,Gender_Male_input]])

In [154]:
stdresult

array([1], dtype=int64)

In [140]:
#preinput=sc.fit_transform([[age_input,EstimatedSalary_input,Gender_Male_input]])

In [142]:
#std_result=classifier.predict(preinput)

In [144]:
#std_result

array([0], dtype=int64)